"""Named constants for the Website Generation Engine (AES-WEB-001 Phase 1).

Constants only. No computation, no imports beyond the standard library
(dependency matrix §3.2). Every magic number in the WGE lives here or
does not exist.
"""

from engines.website_generation.constants.build import (
    ACTIVE_STAGE_SEQUENCE,
    MAX_COGNITION_ATTEMPTS_PER_CELL,
    MAX_DEPLOY_VERIFY_ATTEMPTS,
    MAX_GATE_REWORK_CYCLES,
    PHASE1_EXECUTED_STAGES,
    PIPELINE_VERSION,
    STAGE_ASSEMBLY,
    STAGE_BRAND_RESOLUTION,
    STAGE_CERTIFICATION,
    STAGE_COMPONENT_RESOLUTION,
    STAGE_CONTENT_DRAFTING,
    STAGE_CONTENT_VALIDATION,
    STAGE_GATING,
    STAGE_IA_PLANNING,
    STAGE_LAYOUT_COMPOSITION,
    STAGE_PACKAGING,
    STAGE_RENDERING,
    STAGE_SEO_COMPILATION,
    STAGE_SPEC_COMPILATION,
)

__all__ = [
    "ACTIVE_STAGE_SEQUENCE",
    "MAX_COGNITION_ATTEMPTS_PER_CELL",
    "MAX_DEPLOY_VERIFY_ATTEMPTS",
    "MAX_GATE_REWORK_CYCLES",
    "PHASE1_EXECUTED_STAGES",
    "PIPELINE_VERSION",
    "STAGE_ASSEMBLY",
    "STAGE_BRAND_RESOLUTION",
    "STAGE_CERTIFICATION",
    "STAGE_COMPONENT_RESOLUTION",
    "STAGE_CONTENT_DRAFTING",
    "STAGE_CONTENT_VALIDATION",
    "STAGE_GATING",
    "STAGE_IA_PLANNING",
    "STAGE_LAYOUT_COMPOSITION",
    "STAGE_PACKAGING",
    "STAGE_RENDERING",
    "STAGE_SEO_COMPILATION",
    "STAGE_SPEC_COMPILATION",
]
