"""PTF-MEASUREMENT-001 -- the measurement contract.

The property every test here serves: while the committed configuration is
disabled, nothing this module touches changes a generated byte. The enabled
path is exercised with a hand-built config so its SHAPE is pinned without a
vendor existing.
"""

from __future__ import annotations

import hashlib
import json
import pathlib

import pytest

from scripts.pettripfinder import measurement as M
from scripts.pettripfinder.commercial_actions import (
    ACTION_BOOKING, ACTION_OFFICIAL_WEBSITE, ANALYTICS_JS, EVENT_DIMENSIONS,
    EVENT_OPTIONAL_DIMENSIONS, EVENT_TYPES, build_go_page,
)
from scripts.pettripfinder.release_contracts import REPO_ROOT, load_contract

PAGE = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<title>T</title><link rel="canonical" href="https://pettripfinder.com/x/">'
        '</head><body><main id="main"><p>x</p></main></body></html>')

ENABLED = M.MeasurementConfig(
    enabled=True,
    provider=M.ProviderConfig(
        kind=M.PROVIDER_KIND_BEACON_SCRIPT,
        script_src="https://stats.example.test/script.js",
        event_endpoint="https://stats.example.test/api/event",
        site_domain="pettripfinder.com",
        allowed_hosts=("stats.example.test",)))

CTX = M.PageContext(market="columbus-oh", page_type=M.PAGE_TYPE_HOTEL_PROFILE,
                    route="/pet-friendly-hotels/x/", listing_id="x",
                    category="pet-friendly-hotels", corridor="Dublin",
                    verification_status="VERIFIED_PET_FRIENDLY",
                    build_id="d06681b291fd")


@pytest.fixture(autouse=True)
def _reset_build_state():
    """Measurement config is build state; never let a test leak it."""
    before = M.get_measurement_config()
    yield
    M.set_measurement_config(before)


# --------------------------------------------------------------------------- #
# The committed configuration
# --------------------------------------------------------------------------- #

class TestCommittedConfig:
    def test_the_committed_config_is_disabled_with_no_provider(self):
        cfg = M.load_measurement_config()
        assert cfg.enabled is False
        assert cfg.provider.kind == M.PROVIDER_KIND_NONE
        assert cfg.active is False
        assert cfg.provider.script_src == "" and cfg.provider.event_endpoint == ""
        assert cfg.provider.allowed_hosts == ()

    def test_the_committed_config_names_its_schema(self):
        doc = json.loads(M.CONFIG_PATH.read_text(encoding="utf-8"))
        assert doc["schema"] == M.MEASUREMENT_CONFIG_SCHEMA
        assert M.validate_config_document(doc) == []

    def test_the_default_build_state_is_disabled(self):
        M.set_measurement_config(None)
        assert M.get_measurement_config() is M.DISABLED


class TestConfigValidationFailsClosed:
    def _doc(self, **over):
        doc = {"schema": M.MEASUREMENT_CONFIG_SCHEMA, "enabled": False,
               "provider": {"kind": "none", "script_src": "", "event_endpoint": "",
                            "site_domain": "", "allowed_hosts": []}}
        doc.update(over)
        return doc

    def test_wrong_schema_is_refused(self):
        assert M.validate_config_document(self._doc(schema="x/9"))

    def test_unknown_key_is_refused(self):
        assert M.validate_config_document(self._doc(vendor_id="UA-1"))

    def test_enabled_without_a_provider_is_refused(self):
        problems = M.validate_config_document(self._doc(enabled=True))
        assert any("provider.kind is none" in p for p in problems)
        with pytest.raises(M.MeasurementConfigError):
            M.config_from_document(self._doc(enabled=True))

    def test_a_none_provider_that_still_names_a_script_is_refused(self):
        doc = self._doc()
        doc["provider"]["script_src"] = "https://x.test/s.js"
        assert M.validate_config_document(doc)

    def test_beacon_provider_host_must_be_allowlisted(self):
        doc = self._doc(enabled=True, provider={
            "kind": "beacon_script", "script_src": "https://a.test/s.js",
            "event_endpoint": "https://b.test/e", "site_domain": "pettripfinder.com",
            "allowed_hosts": ["a.test"]})
        problems = M.validate_config_document(doc)
        assert any("event_endpoint host" in p for p in problems)

    def test_beacon_provider_must_be_https(self):
        doc = self._doc(enabled=True, provider={
            "kind": "beacon_script", "script_src": "http://a.test/s.js",
            "event_endpoint": "https://a.test/e", "site_domain": "pettripfinder.com",
            "allowed_hosts": ["a.test"]})
        assert any("https" in p for p in M.validate_config_document(doc))

    def test_a_valid_beacon_config_loads(self):
        doc = self._doc(enabled=True, provider={
            "kind": "beacon_script", "script_src": "https://a.test/s.js",
            "event_endpoint": "https://a.test/e", "site_domain": "pettripfinder.com",
            "allowed_hosts": ["a.test"]})
        assert M.config_from_document(doc).active is True

    def test_missing_file_raises(self, tmp_path):
        with pytest.raises(M.MeasurementConfigError):
            M.load_measurement_config(tmp_path / "nope.json")

    def test_malformed_json_raises(self, tmp_path):
        p = tmp_path / "m.json"
        p.write_text("{not json", encoding="utf-8")
        with pytest.raises(M.MeasurementConfigError):
            M.load_measurement_config(p)


# --------------------------------------------------------------------------- #
# Disabled path: the identity function
# --------------------------------------------------------------------------- #

class TestDisabledPath:
    def test_disabled_injection_returns_the_input_object_unchanged(self):
        out = M.inject_page_measurement(PAGE, CTX, M.DISABLED)
        assert out is PAGE

    def test_disabled_is_byte_identical_across_every_page_type(self):
        for page_type in sorted(M.PAGE_TYPES):
            ctx = M.PageContext(market="columbus-oh", page_type=page_type, route="/x/")
            assert M.inject_page_measurement(PAGE, ctx, M.DISABLED) == PAGE

    def test_disabled_build_state_is_what_the_default_argument_uses(self):
        M.set_measurement_config(M.load_measurement_config())
        assert M.inject_page_measurement(PAGE, CTX) == PAGE

    def test_no_snippet_no_adapter_no_marker_while_disabled(self):
        assert M.provider_head_snippet(M.DISABLED, CTX) == ""
        assert M.provider_adapter_js(M.DISABLED) == ""
        assert M.inline_beacon_provider_js(M.DISABLED) == ""
        assert M.SNIPPET_MARKER not in M.inject_page_measurement(PAGE, CTX, M.DISABLED)

    def test_go_page_with_disabled_adapter_is_todays_go_page(self):
        kwargs = dict(listing_id="x", listing_name="X", action=ACTION_OFFICIAL_WEBSITE,
                      destination="https://x.test/", page_type="listing_profile",
                      category="pet-friendly-hotels")
        _route, plain = build_go_page(**kwargs)
        _route, wired = build_go_page(
            provider_inline_js=M.inline_beacon_provider_js(M.DISABLED), **kwargs)
        assert plain == wired
        assert "build_id" not in plain
        assert '"affiliate_provider": ""' in plain


# --------------------------------------------------------------------------- #
# Enabled path: the shape a later release turns on
# --------------------------------------------------------------------------- #

class TestEnabledPath:
    def test_enabled_injects_exactly_once_before_head_close(self):
        out = M.inject_page_measurement(PAGE, CTX, ENABLED)
        assert out != PAGE
        assert out.count(M.SNIPPET_MARKER) == 2          # the script tag + the inline tag
        assert out.index(M.SNIPPET_MARKER) < out.index("</head>")
        assert out.endswith("</main></body></html>")

    def test_enabled_is_idempotent(self):
        once = M.inject_page_measurement(PAGE, CTX, ENABLED)
        twice = M.inject_page_measurement(once, CTX, ENABLED)
        assert twice == once

    def test_enabled_emits_page_view_and_the_page_types_extra_event(self):
        out = M.inject_page_measurement(PAGE, CTX, ENABLED)
        assert 'ptfAnalytics.emit("page_view"' in out
        assert 'ptfAnalytics.emit("listing_profile_view"' in out
        cmp_ctx = M.PageContext(market="columbus-oh", route="/c/",
                                page_type=M.PAGE_TYPE_POLICY_COMPARISON)
        assert 'ptfAnalytics.emit("policy_comparison_view"' in \
            M.inject_page_measurement(PAGE, cmp_ctx, ENABLED)
        home_ctx = M.PageContext(market="columbus-oh", route="/", page_type=M.PAGE_TYPE_HOME)
        home = M.inject_page_measurement(PAGE, home_ctx, ENABLED)
        assert home.count("ptfAnalytics.emit(") == 1

    def test_enabled_snippet_assigns_the_provider_before_the_interface(self):
        out = M.inject_page_measurement(PAGE, CTX, ENABLED)
        assert out.index("window.__ptfAnalyticsProvider=") < out.index("window.ptfAnalytics =")
        assert ANALYTICS_JS in out

    def test_enabled_dimensions_carry_every_contract_key(self):
        out = M.inject_page_measurement(PAGE, CTX, ENABLED)
        payload = out.split('ptfAnalytics.emit("page_view",', 1)[1].split(");")[0]
        dims = json.loads(payload)
        assert set(dims) == set(EVENT_DIMENSIONS)
        assert dims["build_id"] == "d06681b291fd"
        assert dims["market"] == "columbus-oh" and dims["affiliate_provider"] == ""

    def test_enabled_vendor_script_is_deferred_and_from_the_configured_host(self):
        out = M.inject_page_measurement(PAGE, CTX, ENABLED)
        assert '<script defer src="https://stats.example.test/script.js"' in out

    def test_enabled_refuses_a_page_without_a_head(self):
        with pytest.raises(M.MeasurementConfigError):
            M.inject_page_measurement("<html><body></body></html>", CTX, ENABLED)

    def test_enabled_never_touches_a_go_page_through_the_content_path(self):
        go = M.PageContext(market="columbus-oh", route="/go/x/call/",
                           page_type=M.PAGE_TYPE_GO_REDIRECT)
        assert M.inject_page_measurement(PAGE, go, ENABLED) == PAGE
        with pytest.raises(M.MeasurementConfigError):
            M.provider_head_snippet(ENABLED, go)

    def test_unknown_page_type_is_refused(self):
        with pytest.raises(M.MeasurementConfigError):
            M.inject_page_measurement(
                PAGE, M.PageContext(market="m", route="/", page_type="mystery"), ENABLED)

    def test_script_escape_rule_holds_in_the_snippet(self):
        ctx = M.PageContext(market="columbus-oh", route="/x/",
                            page_type=M.PAGE_TYPE_EDITORIAL, corridor="</script><b>")
        out = M.inject_page_measurement(PAGE, ctx, ENABLED)
        assert "</script><b>" not in out.split("</head>")[0].replace(
            '</script><script', "")  # the only "</script" inside <head> closes our tags


class TestGoAdapter:
    def test_go_adapter_is_inline_and_uses_send_beacon(self):
        js = M.inline_beacon_provider_js(ENABLED)
        assert js.startswith(M.GO_ADAPTER_MARKER)
        assert "navigator.sendBeacon" in js
        assert "window.__ptfAnalyticsProvider=function" in js
        assert "<script" not in js and "src=" not in js
        assert "https://stats.example.test/api/event" in js

    def test_go_page_with_adapter_needs_no_external_script(self):
        _route, page = build_go_page(
            listing_id="x", listing_name="X", action=ACTION_OFFICIAL_WEBSITE,
            destination="https://x.test/", page_type="listing_profile",
            category="pet-friendly-hotels", build_id="d06681b291fd",
            provider_inline_js=M.inline_beacon_provider_js(ENABLED))
        assert "<script src=" not in page and "defer" not in page
        assert page.index("window.__ptfAnalyticsProvider=") < page.index("window.ptfAnalytics =")
        assert page.index("window.ptfAnalytics =") < page.index("ptfAnalytics.emit(")
        assert page.index("ptfAnalytics.emit(") < page.index("location.replace(")
        assert '"build_id": "d06681b291fd"' in page

    def test_go_page_refuses_a_non_hex_build_id(self):
        with pytest.raises(ValueError):
            build_go_page(listing_id="x", listing_name="X", action=ACTION_OFFICIAL_WEBSITE,
                          destination="https://x.test/", page_type="listing_profile",
                          category="pet-friendly-hotels", build_id="<script>")


# --------------------------------------------------------------------------- #
# build_id
# --------------------------------------------------------------------------- #

class TestBuildId:
    def test_build_id_is_the_contracts_package_sha_truncated(self):
        expected = load_contract("columbus-oh")["policy_package"]["expected_sha256"]
        assert M.build_id_for("columbus-oh") == expected[:M.BUILD_ID_LENGTH]
        assert len(M.build_id_for("milwaukee-wi")) == M.BUILD_ID_LENGTH
        assert M.build_id_for("milwaukee-wi") == \
            load_contract("milwaukee-wi")["policy_package"]["expected_sha256"][:12]

    def test_build_id_is_deterministic(self):
        assert M.build_id_for("columbus-oh") == M.build_id_for("columbus-oh")

    def test_build_id_is_market_local(self):
        ids = {m: M.build_id_for(m) for m in ("columbus-oh", "milwaukee-wi", "dayton-oh")}
        assert len(set(ids.values())) == 3

    def test_build_id_does_not_change_when_another_markets_contract_does(self, monkeypatch):
        before = M.build_id_for("columbus-oh")
        from scripts.pettripfinder import release_contracts as RC
        real = RC.load_contract

        def tampered(market_id):
            doc = real(market_id)
            if market_id != "columbus-oh":
                doc = dict(doc, policy_package=dict(doc["policy_package"],
                                                    expected_sha256="0" * 64))
            return doc
        monkeypatch.setattr(RC, "load_contract", tampered)
        assert M.build_id_for("columbus-oh") == before
        assert M.build_id_for("dayton-oh") == "0" * 12

    def test_build_id_reads_no_clock_or_environment(self, monkeypatch):
        monkeypatch.setenv("PTF_BUILD_ID", "should-be-ignored")
        assert M.build_id_for("columbus-oh") == \
            load_contract("columbus-oh")["policy_package"]["expected_sha256"][:12]

    def test_build_id_is_empty_for_a_market_with_no_package(self):
        # Was cincinnati-oh until PTF-CINCINNATI-HARDENED-SYNC-002 gave it a
        # policy package. Detroit-Ann Arbor is the configured market that still
        # commits none, so it is the market this rule can be demonstrated on.
        assert M.build_id_for("detroit-ann-arbor-mi") == ""

    def test_build_id_falls_back_to_the_package_file_without_a_contract(self, monkeypatch):
        from scripts.pettripfinder import release_contracts as RC
        from scripts.pettripfinder.site_data import published_facts_path
        monkeypatch.setattr(RC, "contract_path", lambda mid: pathlib.Path("/nope/x.json"))
        sha = hashlib.sha256(published_facts_path("columbus-oh").read_bytes()).hexdigest()
        assert M.build_id_for("columbus-oh") == sha[:12]


# --------------------------------------------------------------------------- #
# The contract constants
# --------------------------------------------------------------------------- #

class TestContract:
    def test_event_types_are_unchanged(self):
        assert EVENT_TYPES == frozenset({
            "page_view", "listing_impression", "listing_profile_view",
            "filter_applied", "outbound_official_click", "outbound_booking_click",
            "directions_click", "phone_click", "report_change_click",
            "policy_comparison_view"})

    def test_build_id_is_a_declared_dimension_and_filter_value_is_optional(self):
        assert EVENT_DIMENSIONS[-1] == "build_id"
        assert EVENT_DIMENSIONS[:-1] == (
            "market", "page_type", "route", "listing_id", "listing_state",
            "category", "corridor", "action_position", "verification_status",
            "affiliate_provider")
        assert EVENT_OPTIONAL_DIMENSIONS == ("filter_value",)

    def test_page_context_dimensions_match_the_declared_set(self):
        assert set(CTX.dimensions()) == set(EVENT_DIMENSIONS)

    def test_affiliate_booking_page_carries_provider_and_sponsored_rel(self):
        _route, page = build_go_page(
            listing_id="x", listing_name="X", action=ACTION_BOOKING,
            destination="https://aff.test/l", page_type="listing_profile",
            category="pet-friendly-hotels", affiliate_provider="acme")
        assert '"affiliate_provider": "acme"' in page
        assert 'rel="nofollow sponsored noopener"' in page

    def test_an_affiliate_provider_never_changes_rel_on_a_non_booking_action(self):
        _route, page = build_go_page(
            listing_id="x", listing_name="X", action=ACTION_OFFICIAL_WEBSITE,
            destination="https://x.test/", page_type="listing_profile",
            category="pet-friendly-hotels", affiliate_provider="acme")
        assert 'rel="noopener"' in page


# --------------------------------------------------------------------------- #
# Route classification (what the generator's post-pass relies on)
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("route,expected", [
    ("/", M.PAGE_TYPE_HOME),
    ("/about/", M.PAGE_TYPE_EDITORIAL),
    ("/methodology/", M.PAGE_TYPE_EDITORIAL),
    ("/pet-friendly-hotels/", M.PAGE_TYPE_CATEGORY),
    ("/pet-friendly-hotels/policy-comparison/", M.PAGE_TYPE_POLICY_COMPARISON),
    ("/pet-friendly-hotels/aloft-columbus-easton/", M.PAGE_TYPE_HOTEL_PROFILE),
    ("/pet-friendly-parks/", M.PAGE_TYPE_CATEGORY),
    ("/pet-friendly-parks/x-park/", M.PAGE_TYPE_PLACE_PROFILE),
    ("/go/x/call/", M.PAGE_TYPE_GO_REDIRECT),
])
def test_classify_columbus_routes(route, expected):
    assert M.classify_route(route, market_slug="columbus-oh", legacy_unprefixed=True,
                            published_categories=("pet-friendly-hotels",
                                                  "pet-friendly-parks",
                                                  "pet-friendly-restaurants")) == expected


@pytest.mark.parametrize("route,expected", [
    ("/pet-friendly-hotels/", M.PAGE_TYPE_CATEGORY),
    ("/pet-friendly-hotels/milwaukee/", M.PAGE_TYPE_MARKET_HUB),
    ("/pet-friendly-hotels/milwaukee/policy-comparison/", M.PAGE_TYPE_POLICY_COMPARISON),
    ("/pet-friendly-hotels/milwaukee/aloft-by-marriott-milwaukee-downtown/",
     M.PAGE_TYPE_HOTEL_PROFILE),
    ("/go/milwaukee/x/booking/", M.PAGE_TYPE_GO_REDIRECT),
])
def test_classify_prefixed_routes(route, expected):
    assert M.classify_route(route, market_slug="milwaukee", legacy_unprefixed=False,
                            published_categories=("pet-friendly-hotels",)) == expected


# --------------------------------------------------------------------------- #
# Gates, on a synthetic site
# --------------------------------------------------------------------------- #

def _gate(gates, gate_id, passed, detail=""):
    gates[gate_id] = {"pass": bool(passed), "detail": detail}


def _site(tmp_path, pages):
    for route, text in pages.items():
        d = tmp_path / route.strip("/")
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.html").write_text(text, encoding="utf-8")
    return tmp_path


class TestGates:
    def test_all_three_pass_on_a_clean_disabled_site(self, tmp_path):
        site = _site(tmp_path, {"/": PAGE, "/x/": PAGE, "/go/x/call/": "<html></html>"})
        gates = {}
        M.run_measurement_gates(gates, _gate, site)
        assert [g for g in M.MEASUREMENT_GATES if not gates[g]["pass"]] == []

    def test_an_external_script_fails_the_disabled_gate(self, tmp_path):
        leaked = PAGE.replace("</head>", '<script src="https://cdn.test/a.js"></script></head>')
        site = _site(tmp_path, {"/": leaked})
        gates = {}
        M.run_measurement_gates(gates, _gate, site)
        assert not gates[M.GATE_NO_EXTERNAL_WHEN_DISABLED]["pass"]
        assert "/" in gates[M.GATE_NO_EXTERNAL_WHEN_DISABLED]["detail"]

    def test_a_stray_marker_fails_the_once_gate_while_disabled(self, tmp_path):
        site = _site(tmp_path, {"/": M.inject_page_measurement(PAGE, CTX, ENABLED)})
        gates = {}
        M.run_measurement_gates(gates, _gate, site)
        assert not gates[M.GATE_SNIPPET_ONCE]["pass"]

    def test_an_invalid_config_fails_the_config_gate(self, tmp_path):
        bad = tmp_path / "m.json"
        bad.write_text('{"schema": "x"}', encoding="utf-8")
        site = _site(tmp_path / "site", {"/": PAGE})
        gates = {}
        M.run_measurement_gates(gates, _gate, site, config_path=bad)
        assert not gates[M.GATE_CONFIG_VALID]["pass"]

    def test_config_sha_is_the_files_sha(self):
        assert M.config_sha256() == hashlib.sha256(M.CONFIG_PATH.read_bytes()).hexdigest()
        assert (REPO_ROOT / "deploy" / "netlify" / "measurement.json") == M.CONFIG_PATH
