"""PTF-CINCINNATI-PARALLEL-REVALIDATION-002 -- Phase 19, the parallel-safety proof.

Pittsburgh owns the serialized promotion lane while this order runs, and
Louisville may be running its own market-local revalidation at the same time.
This order is parallel-safe ONLY, so the proof is not "I intended to touch
nothing else" -- it is a mechanical read of every path this branch changed
against the base, checked against the prohibitions the order names.

The proof asserts. If a forbidden path appears, this exits non-zero and says
which one.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections import OrderedDict
from datetime import datetime, timezone

_DASH = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
_ROOT = os.path.abspath(os.path.join(_DASH, ".."))
PKG_PREFIX = "atlas-dashboard/launch_packages/pettripfinder/"
OUT = os.path.join(_DASH, "launch_packages", "pettripfinder", "markets", "reports",
                   "cincinnati_oh_parallel_safety_002.json")

BASE = "d06e2eba07dc95edda745d31c51e53edad72983a"

# Each rule is (label, matcher, why it is forbidden here).
FORBIDDEN = [
    ("pittsburgh_files", re.compile(r"pittsburgh", re.I),
     "Pittsburgh owns the serialized promotion lane while this order runs"),
    ("louisville_files", re.compile(r"louisville", re.I),
     "Louisville may be running its own market-local revalidation concurrently"),
    ("indianapolis_files", re.compile(r"indianapolis", re.I),
     "Indianapolis is the current deployed lineage and this branch predates it"),
    ("cincinnati_authority", re.compile(r"launch_packages/pettripfinder/markets/authority/"),
     "this order may read authority and may never write it"),
    ("identity_census", re.compile(r"launch_packages/pettripfinder/identity_census"),
     "a census change is a promotion, not a revalidation"),
    ("final_partition", re.compile(r"launch_packages/pettripfinder/\w*_final_partition"),
     "the partition is the pinned source of truth; the shadow moves, the partition does not"),
    ("generated_globals", re.compile(
        r"launch_packages/pettripfinder/(hotel_policy_facts\.json|hotel_exclusions\.json"
        r"|identity_routing\.json|seed_businesses\.csv|ptf_global_authority_manifest\.json)$"),
     "the three generated globals and the manifest are regenerated by a serialized order"),
    ("market_policy_packages", re.compile(r"launch_packages/pettripfinder/hotel_policy_facts_"),
     "a policy package change is an application, not a revalidation"),
    ("current_state_pins", re.compile(r"tests/pettripfinder/pins/"),
     "the current-state pins are shared and only a serialized order moves them"),
    ("shared_ledgers", re.compile(
        r"launch_packages/pettripfinder/(ptf_paid_attempt_ledger|ptf_discovery_attempt_ledger"
        r"|ptf_paid_attempt_audit)")," this order reads the shared ledgers and never writes them"),
    ("deployment_files", re.compile(
        r"(netlify\.toml|_headers|_redirects|deployment_packet|deploy)", re.I),
     "no deployment artifact may move in a parallel-safe order"),
    ("release_contracts", re.compile(r"launch_packages/pettripfinder/markets/coverage/"),
     "a release contract is re-authored by the application order, not by this one"),
    ("site_bundle", re.compile(r"^atlas-dashboard/(site|dist|build|public)/"),
     "no production assembly output may exist"),
]

# A shared file this order IS allowed to touch, and the exact reason.
ALLOWED_SHARED = {
    "atlas-dashboard/tests/pettripfinder/acquisition/test_store_integration_025.py":
        "run-registration bookkeeping. Phase 19 permits adding Cincinnati only, and the diff adds four "
        "cincinnati_oh_* run ids to OTHER_MARKET_RUNS and changes nothing else.",
    "atlas-dashboard/tests/pettripfinder/test_regression_delta_001.py":
        "closure of a TRUE_NEW failure this order's own registration commit opened. The replay fixture "
        "built its BEFORE from the live registration file, so once this branch actually applied that "
        "registration the edit under test became a no-op. The fixture now strips those two elements back "
        "out before committing its base. No assertion changed and no market is named.",
    "atlas-dashboard/launch_packages/pettripfinder/reports/factory_throughput_001_test_inventory.json":
        "generated description of the suite, regenerated because carrying revalidation 001's pin "
        "migration onto this base moved 32 restated sites onto the shared pins. It is a report ABOUT the "
        "tests, never authority, and no market's counts live in it.",
    "atlas-dashboard/launch_packages/pettripfinder/reports/factory_throughput_001_test_inventory.md":
        "the same generated inventory in its readable form, regenerated in the same call.",
}


def changed_paths(base, head):
    out = subprocess.run(["git", "diff", "--name-only", "%s..%s" % (base, head)],
                         cwd=_ROOT, capture_output=True, text=True, check=True)
    paths = [p for p in out.stdout.splitlines() if p.strip()]
    staged = subprocess.run(["git", "diff", "--cached", "--name-only"],
                            cwd=_ROOT, capture_output=True, text=True, check=True)
    paths.extend(p for p in staged.stdout.splitlines() if p.strip())
    unstaged = subprocess.run(["git", "diff", "--name-only"],
                              cwd=_ROOT, capture_output=True, text=True, check=True)
    paths.extend(p for p in unstaged.stdout.splitlines() if p.strip())
    return sorted(set(paths))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default=BASE)
    parser.add_argument("--head", default="HEAD")
    args = parser.parse_args()

    paths = changed_paths(args.base, args.head)
    violations = []
    checks = OrderedDict()
    for label, matcher, why in FORBIDDEN:
        hits = [p for p in paths if matcher.search(p) and p not in ALLOWED_SHARED]
        checks[label] = OrderedDict([("files_changed", len(hits)), ("why_forbidden", why),
                                     ("files", hits)])
        violations.extend((label, p) for p in hits)

    cincinnati_local = [p for p in paths if "cincinnati" in p.lower()]
    shared = [p for p in paths if p in ALLOWED_SHARED]
    unaccounted = [p for p in paths if p not in cincinnati_local and p not in shared]

    report = OrderedDict()
    report["schema"] = "ptf-parallel-safety-proof/1.0"
    report["work_order"] = "PTF-CINCINNATI-PARALLEL-REVALIDATION-002"
    report["market_id"] = "cincinnati-oh"
    report["phase"] = "19 -- parallel safety"
    report["as_of"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    report["base"] = args.base
    report["method"] = ("every path this branch changed against its base, read from git and matched against "
                        "the prohibitions the order names. This is a mechanical read, not an assertion of "
                        "intent.")
    report["total_paths_changed"] = len(paths)
    report["cincinnati_market_local_paths"] = len(cincinnati_local)
    report["shared_paths_touched"] = len(shared)
    report["shared_paths_and_why_each_is_allowed"] = {p: ALLOWED_SHARED[p] for p in shared}
    report["paths_accounted_for_by_neither_rule"] = unaccounted
    report["checks"] = checks
    report["production_assembly"] = "NOT RUN -- no assembler was invoked and no bundle directory exists"
    report["deployment"] = "NOT RUN"
    report["promotion"] = "NOT RUN"
    report["PARALLEL_SAFE"] = not violations and not unaccounted
    report["violations"] = [{"rule": r, "path": p} for r, p in violations]
    report["changed_paths"] = paths

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2)
        handle.write("\n")

    print("wrote", OUT)
    for label, check in checks.items():
        print("  %-24s %d" % (label, check["files_changed"]))
    print("cincinnati-local %d | allowed-shared %d | unaccounted %d"
          % (len(cincinnati_local), len(shared), len(unaccounted)))
    print("PARALLEL_SAFE:", report["PARALLEL_SAFE"])
    if violations or unaccounted:
        for rule, path in violations:
            print("  VIOLATION", rule, path)
        for path in unaccounted:
            print("  UNACCOUNTED", path)
        sys.exit(1)


if __name__ == "__main__":
    main()
