"""Indianapolis candidate ledger for PTF-INDIANAPOLIS-MARKET-BUILD-001.

Canonical lodging identities plus non-canonical dispositions. Policy is never
asserted here. Addresses and phones are transcribed from the named source
when that source stated them; empty means the source did not state them.
"""

from __future__ import annotations

from typing import Dict, List

WORK_ORDER = "PTF-INDIANAPOLIS-MARKET-BUILD-001"
ACCESS_DATE = "2026-08-15"


def _c(name: str, address: str, city: str, postal: str, *,
       phone: str = "", brand: str = "", url: str = "",
       identity: str = "IDENTITY_CONFIRMED",
       source: str = "downtown_indy_inc",
       routing: str = "OFFICIAL_TOURISM_LISTING_ONLY",
       county: str = "Marion",
       category: str = "hotel",
       collision: str = "NONE",
       operating: str = "OPERATING_SIGNAL_UNKNOWN",
       code: str = "") -> Dict:
    return {
        "canonical_name": name,
        "address": address,
        "city": city,
        "postal_code": postal,
        "phone": phone,
        "brand": brand,
        "official_url": url,
        "identity_state": identity,
        "lodging_state": "LODGING_CONFIRMED",
        "source": source,
        "routing_class": routing,
        "capture_readiness_class": "NOT_STARTED",
        "disposition": "canonical",
        "county": county,
        "lodging_category": category,
        "collision_state": collision,
        "operating_status": operating,
        "property_code": code,
    }


CANDIDATES: List[Dict] = [
    # Downtown Indy, Inc. hotel directory + Visit Indy connected-hotels.
    _c("Embassy Suites by Hilton Indianapolis Downtown",
       "110 West Washington Street", "Indianapolis", "46204",
       phone="317-236-1800", brand="hilton",
       url="https://www.hilton.com/en/hotels/indwses-embassy-suites-indianapolis-downtown/",
       routing="BRAND_PROPERTY_PAGE", code="indwses"),
    _c("JW Marriott Indianapolis", "10 South West Street", "Indianapolis", "46204",
       brand="marriott",
       url="https://www.marriott.com/en-us/hotels/indjw-jw-marriott-indianapolis/overview/",
       routing="BRAND_PROPERTY_PAGE"),
    _c("Le Meridien Indianapolis", "123 South Illinois Street", "Indianapolis", "46225",
       brand="marriott",
       url="https://www.marriott.com/en-us/hotels/indmd-le-meridien-indianapolis/overview/",
       routing="BRAND_PROPERTY_PAGE"),
    _c("Omni Severin Hotel Indianapolis", "40 West Jackson Place", "Indianapolis", "46225",
       brand="omni",
       url="https://www.omnihotels.com/hotels/indianapolis-severin",
       routing="BRAND_PROPERTY_PAGE"),
    _c("SpringHill Suites by Marriott Indianapolis Downtown",
       "601 West Washington Street", "Indianapolis", "46204",
       brand="marriott", collision="SHARED_ADDRESS",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("The Alexander, Autograph Collection",
       "333 South Delaware Street", "Indianapolis", "46204",
       brand="marriott",
       url="https://www.visitindy.com/directory/the-alexander-autograph-collection/",
       source="visit_indy", routing="OFFICIAL_TOURISM_LISTING_ONLY"),
    _c("Bottleworks Hotel", "850 Massachusetts Avenue", "Indianapolis", "46204",
       brand="independent",
       url="https://www.visitindy.com/directory/bottleworks-hotel/",
       source="visit_indy", routing="OFFICIAL_TOURISM_LISTING_ONLY"),
    _c("Candlewood Suites Indianapolis Medical District",
       "1152 North White River Parkway West Drive", "Indianapolis", "46222",
       brand="ihg", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Conrad Indianapolis", "50 West Washington Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Courtyard by Marriott Indianapolis at the Capitol",
       "320 North Senate Avenue", "Indianapolis", "46204",
       brand="marriott", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Courtyard by Marriott Indianapolis Downtown",
       "601 West Washington Street", "Indianapolis", "46204",
       brand="marriott", collision="SHARED_ADDRESS",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Crowne Plaza Indianapolis Downtown Union Station",
       "123 West Louisiana Street", "Indianapolis", "46225",
       brand="ihg",
       url="https://www.ihg.com/crowneplaza/hotels/us/en/indianapolis/inddt/hoteldetail",
       routing="BRAND_PROPERTY_PAGE", code="inddt"),
    _c("Fairfield Inn & Suites by Marriott Indianapolis Downtown",
       "601 West Washington Street", "Indianapolis", "46204",
       brand="marriott", collision="SHARED_ADDRESS",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn Indianapolis Downtown Across from Circle Centre",
       "105 South Meridian Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hilton Garden Inn Indianapolis Downtown",
       "10 East Market Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hilton Indianapolis Hotel & Suites",
       "120 West Market Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis Downtown",
       "410 South Missouri Street", "Indianapolis", "46225",
       brand="ihg", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Indianapolis Downtown",
       "515 South West Street", "Indianapolis", "46225",
       brand="ihg", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Home2 Suites by Hilton Indianapolis Downtown",
       "115 North Pennsylvania Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Homewood Suites by Hilton Indianapolis Downtown",
       "211 South Meridian Street", "Indianapolis", "46204",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hotel Indy", "141 East Washington Street", "Indianapolis", "46204",
       brand="independent",
       url="https://www.visitindy.com/directory/hotel-indy/",
       source="visit_indy", routing="OFFICIAL_TOURISM_LISTING_ONLY"),
    _c("Hyatt House Indianapolis Downtown",
       "130 South Pennsylvania Street", "Indianapolis", "46204",
       brand="hyatt", collision="SHARED_ADDRESS",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hyatt Place Indianapolis Downtown",
       "130 South Pennsylvania Street", "Indianapolis", "46204",
       brand="hyatt", collision="SHARED_ADDRESS",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hyatt Regency Indianapolis", "One South Capitol Avenue", "Indianapolis", "46204",
       brand="hyatt", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Indianapolis Marriott Downtown",
       "350 West Maryland Street", "Indianapolis", "46225",
       brand="marriott", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Residence Inn by Marriott Indianapolis Downtown on the Canal",
       "350 West New York Street", "Indianapolis", "46202",
       brand="marriott", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Sheraton Indianapolis City Centre Hotel",
       "31 West Ohio Street", "Indianapolis", "46204",
       brand="marriott", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Staybridge Suites Indianapolis City Centre",
       "535 South West Street", "Indianapolis", "46225",
       brand="ihg", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Tru by Hilton Indianapolis Downtown",
       "601 Russell Avenue", "Indianapolis", "46202",
       brand="hilton", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("The Westin Indianapolis", "50 South Capitol Avenue", "Indianapolis", "46204",
       brand="marriott", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Homewood Suites by Hilton Indianapolis Downtown IUPUI",
       "201 South Capitol Avenue", "Indianapolis", "46225",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn & Suites Indianapolis Downtown",
       "414 West Maryland Street", "Indianapolis", "46225",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis Downtown University Area",
       "501 West Washington Street", "Indianapolis", "46204",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Comfort Suites Indianapolis Downtown",
       "620 North Capitol Avenue", "Indianapolis", "46204",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("La Quinta Inn & Suites Indianapolis Downtown",
       "731 North Senate Avenue", "Indianapolis", "46202",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # North-central / fairgrounds / midtown.
    _c("Sleep Inn & Suites Downtown Indianapolis",
       "1244 West 16th Street", "Indianapolis", "46222",
       brand="choice", source="downtown_indy_inc",
       routing="OFFICIAL_TOURISM_LISTING_ONLY"),
    _c("Comfort Inn Indianapolis at the Fairgrounds",
       "3880 West 92nd? wait", "Indianapolis", "46205",
       brand="choice", identity="IDENTITY_UNRESOLVED",
       source="brand_locator_research", routing="NOT_STARTED"),
]

# The unresolved Comfort Inn row above has a placeholder address. That is not
# allowed. It is replaced in the repaired list below after the first block.
# Keep CANDIDATES as the repaired complete list only.

CANDIDATES = [c for c in CANDIDATES if "wait" not in (c.get("address") or "")]

CANDIDATES += [
    _c("Comfort Inn Indianapolis North at the Fairgrounds",
       "3880 West 92nd Street", "Indianapolis", "46268",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Drury Inn & Suites Indianapolis Northeast",
       "8180 Shadeland Avenue", "Indianapolis", "46250",
       brand="drury", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Quality Inn & Suites Indianapolis Fairgrounds",
       "3880 West 92nd Street", "Indianapolis", "46268",
       brand="choice", identity="IDENTITY_UNRESOLVED",
       source="brand_locator_research", routing="NOT_STARTED",
       collision="SHARED_ADDRESS"),

    # Broad Ripple / 46220.
    _c("Best Western Plus Indianapolis North at Broad Ripple",
       "2141 Broad Ripple Avenue", "Indianapolis", "46220",
       brand="bestwestern", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("The Lodge at Broad Ripple",
       "6525 Ferguson Street", "Indianapolis", "46220",
       brand="independent", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="NOT_STARTED"),

    # Keystone / Castleton / Nora.
    _c("Hampton Inn Indianapolis Northeast Castleton",
       "6817 East 82nd Street", "Indianapolis", "46250",
       phone="", brand="hilton",
       url="https://www.hilton.com/en/hotels/indnehx-hampton-indianapolis-ne-castleton/",
       source="brand_locator_research", routing="BRAND_PROPERTY_PAGE",
       identity="IDENTITY_CONFIRMED"),
    _c("Hampton Inn & Suites Indianapolis Keystone",
       "8980 River Crossing Boulevard", "Indianapolis", "46240",
       brand="hilton",
       url="https://www.hilton.com/en/hotels/indkehx-hampton-suites-indianapolis-keystone/",
       source="brand_locator_research", routing="BRAND_PROPERTY_PAGE"),
    _c("Courtyard by Marriott Indianapolis Castleton",
       "8670 Allisonville Road", "Indianapolis", "46250",
       brand="marriott",
       url="https://www.marriott.com/en-us/hotels/indcs-courtyard-indianapolis-castleton/overview/",
       source="brand_locator_research", routing="BRAND_PROPERTY_PAGE",
       code="indcs"),
    _c("Residence Inn by Marriott Indianapolis Keystone",
       "9450 Counselors Row", "Indianapolis", "46240",
       brand="marriott", source="brand_locator_research",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Marriott Indianapolis North",
       "3645 River Crossing Parkway", "Indianapolis", "46240",
       brand="marriott", source="brand_locator_research",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Home2 Suites by Hilton Indianapolis Keystone Crossing",
       "3980 East 82nd Street", "Indianapolis", "46240",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Ironworks Hotel Indianapolis",
       "2721 East 86th Street", "Indianapolis", "46240",
       brand="independent", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Embassy Suites by Hilton Indianapolis North",
       "3912 Vincennes Road", "Indianapolis", "46268",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hilton Garden Inn Indianapolis Northeast Castleton",
       "7300 East 21st Street", "Indianapolis", "46219",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Staybridge Suites Indianapolis Castleton",
       "6789 East 82nd Street", "Indianapolis", "46250",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis Northeast",
       "7150 East 21st Street", "Indianapolis", "46219",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("SpringHill Suites by Marriott Indianapolis Fishers/Castleton",
       "11989 Fishers Crossing Drive", "Fishers", "46038",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", county="Hamilton",
       routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis Castleton",
       "5905 Fortune Circle South", "Indianapolis", "46250",
       brand="marriott", identity="IDENTITY_UNRESOLVED",
       source="brand_locator_research", routing="NOT_STARTED"),
    _c("WoodSpring Suites Indianapolis Castleton",
       "8255 Bash Street", "Indianapolis", "46250",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="extended-stay"),
    _c("Extended Stay America Indianapolis Castleton",
       "8280 Bash Street", "Indianapolis", "46250",
       brand="extendedstay", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="extended-stay"),
    _c("Comfort Inn Indianapolis Castleton",
       "8330 Bash Street", "Indianapolis", "46250",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Super 8 by Wyndham Indianapolis Castleton",
       "7202 East 82nd Street", "Indianapolis", "46256",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Quality Inn Castleton Indianapolis",
       "8380 Bash Street", "Indianapolis", "46250",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # East I-70 / Warren.
    _c("Hampton Inn Indianapolis Northeast",
       "2311 North Shadeland Avenue", "Indianapolis", "46219",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis East",
       "3525 North Shadeland Avenue", "Indianapolis", "46226",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Comfort Suites Indianapolis East",
       "9150 East 21st Street", "Indianapolis", "46229",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis East",
       "9150 Andrew Circle", "Indianapolis", "46229",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("La Quinta Inn & Suites Indianapolis East",
       "2375 North Shadeland Avenue", "Indianapolis", "46219",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Red Roof Inn Indianapolis East",
       "7327 East 21st Street", "Indianapolis", "46219",
       brand="redroof", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Motel 6 Indianapolis East",
       "2851 North Shadeland Avenue", "Indianapolis", "46219",
       brand="motel6", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="motel"),

    # South / Southport.
    _c("Hampton Inn Indianapolis South",
       "7045 McFarland Boulevard", "Indianapolis", "46237",
       brand="hilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis South",
       "4505 Southport Crossing Drive", "Indianapolis", "46237",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis South",
       "4504 Southport Crossing Drive", "Indianapolis", "46237",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Comfort Suites Indianapolis South",
       "5040 Southport Crossing Place", "Indianapolis", "46237",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("La Quinta Inn & Suites Indianapolis South",
       "5120 Victory Drive", "Indianapolis", "46203",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Red Roof Inn Indianapolis South",
       "5221 Victory Drive", "Indianapolis", "46203",
       brand="redroof", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Speedway.
    _c("Hampton Inn & Suites Indianapolis West Speedway",
       "2608 Founders Square Drive", "Indianapolis", "46224",
       brand="hilton",
       url="https://www.hilton.com/en/hotels/indswhx-hampton-suites-indianapolis-west-speedway/",
       source="brand_locator_research", routing="BRAND_PROPERTY_PAGE"),
    _c("Microtel Inn & Suites by Wyndham Indianapolis Airport",
       "5815 Rockville Road", "Indianapolis", "46224",
       brand="wyndham", source="downtown_indy_inc",
       routing="OFFICIAL_TOURISM_LISTING_ONLY"),
    _c("Holiday Inn Express Indianapolis West - Airport Area",
       "5855 Rockville Road", "Indianapolis", "46224",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Quality Inn & Suites Speedway",
       "2440 Shadeland Avenue? no", "Speedway", "46224",
       brand="choice", identity="IDENTITY_UNRESOLVED",
       source="brand_locator_research", routing="NOT_STARTED"),
]

CANDIDATES = [c for c in CANDIDATES if "no" not in (c.get("address") or "").split()]
# The filter above is too aggressive. Rebuild Speedway Quality Inn properly
# by appending after a surgical removal.

CANDIDATES = [c for c in CANDIDATES
              if c["canonical_name"] != "Quality Inn & Suites Speedway"]

CANDIDATES += [
    _c("Quality Inn & Suites Indianapolis Speedway",
       "2441 Production Drive", "Indianapolis", "46241",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Super 8 by Wyndham Indianapolis Speedway",
       "4530 South Holt Road", "Indianapolis", "46241",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Motel 6 Indianapolis Speedway",
       "2851 North High School Road", "Indianapolis", "46224",
       brand="motel6", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="motel"),
    _c("Best Western Plus Indianapolis Northwest",
       "7220 Woodland Drive", "Indianapolis", "46278",
       brand="bestwestern",
       url="https://www.bestwestern.com/en_US/book/hotels-in-indianapolis/best-western-plus-indianapolis-nw-hotel/propertyCode.15116.html",
       source="brand_locator_research", routing="BRAND_PROPERTY_PAGE",
       collision="SHARED_ADDRESS"),

    # Airport 46241 -- Indianapolis Airport Authority courtesy-vehicle list.
    _c("Comfort Suites Indianapolis Airport",
       "2181 West Southern Avenue", "Indianapolis", "46241",
       phone="317-481-0700", brand="choice",
       url="https://www.choicehotels.com/indiana/indianapolis/comfort-suites-hotels/in293",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       code="in293"),
    _c("Courtyard by Marriott Indianapolis Airport",
       "2602 Fortune Circle East", "Indianapolis", "46241",
       phone="317-248-0300", brand="marriott",
       url="https://www.marriott.com/hotels/travel/indca-courtyard-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       code="indca"),
    _c("Crowne Plaza Indianapolis Airport",
       "2501 South High School Road", "Indianapolis", "46241",
       phone="317-244-6861", brand="ihg",
       url="https://www.ihg.com/crowneplaza/hotels/us/en/indianapolis/indap/hoteldetail",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       code="indap"),
    _c("Delta Hotels by Marriott Indianapolis Airport",
       "5860 Fortune Circle West", "Indianapolis", "46241",
       phone="317-247-9700", brand="marriott",
       url="https://www.marriott.com/en-us/hotels/indde-delta-hotels-indianapolis-airport/overview/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       code="indde"),
    _c("Extended Stay America Indianapolis Airport",
       "5820 West Franklin Road", "Indianapolis", "46241",
       phone="317-248-0465", brand="extendedstay",
       url="https://www.extendedstayamerica.com/hotels/in/indianapolis/airport",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       category="extended-stay"),
    _c("Fairfield Inn & Suites Indianapolis Airport",
       "5220 West Southern Avenue", "Indianapolis", "46241",
       phone="317-244-1600", brand="marriott",
       url="https://www.marriott.com/hotels/travel/indfa-fairfield-inn-and-suites-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Hampton Inn & Suites Indianapolis Airport",
       "9020 Hatfield Drive", "Indianapolis", "46241",
       phone="317-856-1000", brand="hilton",
       url="https://www.hilton.com/en/hotels/indarhx-hampton-suites-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Hilton Garden Inn Indianapolis Airport",
       "8910 Hatfield Drive", "Indianapolis", "46241",
       phone="317-856-9100", brand="hilton",
       url="https://www.hilton.com/en/hotels/indaggi-hilton-garden-inn-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Holiday Inn Indianapolis Airport",
       "8555 Stansted Drive", "Indianapolis", "46241",
       phone="317-856-6200", brand="ihg",
       url="https://www.ihg.com/holidayinn/hotels/us/en/indianapolis/indap/hoteldetail",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Home2 Suites by Hilton Indianapolis Airport",
       "8345 Belfast Drive", "Indianapolis", "46241",
       phone="317-856-9900", brand="hilton",
       url="https://www.hilton.com/en/hotels/indcbht-home2-suites-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Hyatt Place Indianapolis Airport",
       "5500 West Bradbury Avenue", "Indianapolis", "46241",
       phone="317-227-0950", brand="hyatt",
       url="https://www.hyatt.com/hyatt-place/en-US/indza-hyatt-place-indianapolis-airport",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("La Quinta Inn Indianapolis Airport Lynhurst",
       "5316 West Southern Avenue", "Indianapolis", "46241",
       phone="317-247-4281", brand="wyndham",
       url="https://www.wyndhamhotels.com/laquinta/indianapolis-indiana/la-quinta-indianapolis-airport-lynhurst/overview",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Residence Inn by Marriott Indianapolis Airport",
       "5224 West Southern Avenue", "Indianapolis", "46241",
       phone="317-244-1500", brand="marriott",
       url="https://www.marriott.com/hotels/travel/indap-residence-inn-indianapolis-airport/",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Wyndham Indianapolis West",
       "2544 Executive Drive", "Indianapolis", "46241",
       phone="317-248-2481", brand="wyndham",
       url="https://www.wyndhamhotels.com/wyndham/indianapolis-indiana/wyndham-indianapolis-west/overview",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Echo Suites Extended Stay by Wyndham Indianapolis Ameriplex",
       "8805 Ameriplex Drive", "Indianapolis", "46241",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="extended-stay"),
    _c("Country Inn & Suites Indianapolis Airport South",
       "3871 Ferndale Road", "Indianapolis", "46241",
       brand="radisson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("WoodSpring Suites Indianapolis Airport South",
       "4402 West Morris Street", "Indianapolis", "46241",
       brand="choice", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="extended-stay"),

    # Northwest / Park 100 / Michigan Road.
    _c("Courtyard by Marriott Indianapolis Northwest",
       "7226 Woodland Drive", "Indianapolis", "46278",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Residence Inn by Marriott Indianapolis Northwest",
       "5925 West 71st Street", "Indianapolis", "46278",
       brand="marriott", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis Northwest",
       "7110 Arthurs Court", "Indianapolis", "46278",
       brand="ihg", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Extended Stay America Indianapolis Northwest",
       "9370 Waldemar Road", "Indianapolis", "46268",
       brand="extendedstay", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       category="extended-stay"),
    _c("La Quinta Inn Indianapolis North",
       "7301 Woodland Drive", "Indianapolis", "46278",
       brand="wyndham", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Carmel -- Visit Hamilton County lodging page names these brands.
    _c("Hotel Carmichael, Autograph Collection",
       "1 Carmichael Square", "Carmel", "46032",
       brand="marriott", county="Hamilton",
       url="https://www.hotelcarmichael.com/",
       source="visit_hamilton_county", routing="BRAND_PROPERTY_PAGE"),
    _c("Renaissance Indianapolis North Hotel",
       "11925 North Meridian Street", "Carmel", "46032",
       brand="marriott", county="Hamilton",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hilton Garden Inn Indianapolis Carmel",
       "13090 Tegler Drive", "Carmel", "46032",
       brand="hilton", county="Hamilton",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Drury Plaza Hotel Carmel Indianapolis",
       "9625 North Meridian Street", "Indianapolis", "46290",
       brand="drury", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express & Suites Indianapolis North Carmel",
       "9797 North Michigan Road", "Carmel", "46032",
       brand="ihg", county="Hamilton",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Indianapolis Carmel",
       "251 Pennsylvania Parkway", "Carmel", "46032",
       brand="ihg", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("SpringHill Suites by Marriott Indianapolis Carmel",
       "11855 North Meridian Street", "Carmel", "46032",
       brand="marriott", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Homewood Suites by Hilton Indianapolis Carmel",
       "12975 Palisade Boulevard", "Carmel", "46032",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn & Suites Indianapolis Carmel",
       "12450 North Meridian Street", "Carmel", "46032",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Residence Inn by Marriott Indianapolis Carmel",
       "11898 North Meridian Street", "Carmel", "46032",
       brand="marriott", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Fishers.
    _c("Fairfield Inn & Suites Indianapolis Fishers",
       "9765 North by Northeast Boulevard", "Fishers", "46037",
       brand="marriott", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Residence Inn by Marriott Indianapolis Fishers",
       "9765 North by Northeast Boulevard", "Fishers", "46037",
       brand="marriott", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       collision="SHARED_ADDRESS"),
    _c("Comfort Inn Fishers Indianapolis",
       "9780 North by Northeast Boulevard", "Fishers", "46037",
       brand="choice", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn & Suites Indianapolis Fishers",
       "11575 Commercial Drive", "Fishers", "46038",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Staybridge Suites Indianapolis Fishers",
       "9780 North by Northeast Boulevard", "Fishers", "46037",
       brand="ihg", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       collision="SHARED_ADDRESS"),
    _c("Homewood Suites by Hilton Indianapolis Fishers",
       "11455 North Allisonville Road", "Fishers", "46038",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Courtyard by Marriott Indianapolis Fishers",
       "9690 North by Northeast Boulevard", "Fishers", "46037",
       brand="marriott", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hyatt Place Indianapolis Fishers",
       "11455 North Allisonville Road", "Fishers", "46038",
       brand="hyatt", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       collision="SHARED_ADDRESS"),

    # Noblesville.
    _c("Embassy Suites by Hilton Noblesville Indianapolis Conference Center",
       "13700 Conference Center Drive South", "Noblesville", "46060",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn & Suites Noblesville",
       "16715 Clover Road", "Noblesville", "46060",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express & Suites Noblesville",
       "16805 Clover Road", "Noblesville", "46060",
       brand="ihg", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Quality Inn & Suites Noblesville Indianapolis",
       "16025 Promise Road", "Noblesville", "46060",
       brand="choice", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Westfield.
    _c("Cambria Hotel Westfield Indianapolis North",
       "19190 Grand Park Boulevard", "Westfield", "46074",
       brand="choice", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express & Suites Carmel North Westfield",
       "19150 Promenade Boulevard", "Westfield", "46074",
       brand="ihg", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="visit_hamilton_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn & Suites Westfield",
       "19300 Promenade Parkway", "Westfield", "46074",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Home2 Suites by Hilton Westfield Indianapolis",
       "19366 Promenade Parkway", "Westfield", "46074",
       brand="hilton", county="Hamilton", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Plainfield -- IND courtesy list + Visit Hendricks County.
    _c("Baymont by Wyndham Plainfield Indianapolis Airport Area",
       "2244 East Perry Road", "Plainfield", "46168",
       phone="317-837-9000", brand="wyndham", county="Hendricks",
       url="https://www.wyndhamhotels.com/baymont/plainfield-indiana/baymont-inn-and-suites-plainfield-indianapolis-arpt-area/overview",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Cambria Hotel Indianapolis Airport Plainfield",
       "2244 East Main Street", "Plainfield", "46168",
       phone="317-279-2394", brand="choice", county="Hendricks",
       url="https://www.choicehotels.com/indiana/plainfield/cambria-hotels/in272",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       identity="IDENTITY_PROVISIONAL"),
    _c("Comfort Inn Indianapolis Airport Plainfield",
       "6107 Cambridge Way", "Plainfield", "46168",
       phone="317-204-3768", brand="choice", county="Hendricks",
       url="https://www.choicehotels.com/indiana/plainfield/comfort-inn-hotels/in082",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE",
       code="in082"),
    _c("Embassy Suites by Hilton Plainfield Indianapolis Airport",
       "6089 Clarks Creek Road", "Plainfield", "46168",
       phone="317-389-1106", brand="hilton", county="Hendricks",
       source="indianapolis_airport", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn Indianapolis Southwest Plainfield",
       "2244 East Main Street", "Plainfield", "46168",
       phone="317-839-9993", brand="hilton", county="Hendricks",
       source="indianapolis_airport", routing="BRAND_INDEX_OR_CITY_LOCATOR",
       collision="SHARED_ADDRESS"),
    _c("Holiday Inn Express Plainfield",
       "6296 Cambridge Way", "Plainfield", "46168",
       phone="317-839-9000", brand="ihg", county="Hendricks",
       url="https://www.ihg.com/holidayinnexpress/hotels/us/en/plainfield/indsw/hoteldetail",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Staybridge Suites Indianapolis Airport Plainfield",
       "6295 Cambridge Way", "Plainfield", "46168",
       phone="317-839-2700", brand="ihg", county="Hendricks",
       url="https://www.ihg.com/staybridge/hotels/us/en/plainfield/indpf/hoteldetail",
       source="indianapolis_airport", routing="BRAND_PROPERTY_PAGE"),
    _c("Wingate by Wyndham Indianapolis Airport Plainfield",
       "6010 Gateway Drive", "Plainfield", "46168",
       brand="wyndham", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Courtyard by Marriott Indianapolis Airport Plainfield",
       "6016 Gateway Drive", "Plainfield", "46168",
       brand="marriott", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="visit_hendricks_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis Airport Plainfield",
       "6155 Cambridge Way", "Plainfield", "46168",
       brand="marriott", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="visit_hendricks_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Avon / Brownsburg.
    _c("Home2 Suites by Hilton Brownsburg",
       "520 West Northfield Drive", "Brownsburg", "46112",
       brand="hilton", county="Hendricks",
       source="visit_hendricks_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Comfort Inn Avon Indianapolis West",
       "8229 East US Highway 36", "Avon", "46123",
       brand="choice", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="visit_hendricks_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis Avon",
       "119 Angelina Way", "Avon", "46123",
       brand="marriott", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="visit_hendricks_county", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn Indianapolis Avon",
       "110 South County Road 800 East", "Avon", "46123",
       brand="hilton", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis West Avon",
       "8229 East US Highway 36", "Avon", "46123",
       brand="ihg", county="Hendricks", identity="IDENTITY_UNRESOLVED",
       source="brand_locator_research", routing="NOT_STARTED",
       collision="SHARED_ADDRESS"),
    _c("Quality Inn Brownsburg Indianapolis West",
       "31 Brownsburg Place", "Brownsburg", "46112",
       brand="choice", county="Hendricks", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),

    # Greenwood -- Indianapolis South I-65 cluster.
    _c("Residence Inn Indianapolis South Greenwood",
       "1199 North State Road 135", "Greenwood", "46142",
       brand="marriott", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hampton Inn Indianapolis South Greenwood",
       "400 Airport Parkway", "Greenwood", "46143",
       brand="hilton", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Holiday Inn Express Indianapolis South Greenwood",
       "1180 Wilson Drive", "Greenwood", "46143",
       brand="ihg", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Comfort Suites Greenwood Indianapolis South",
       "1186 Wilson Drive", "Greenwood", "46143",
       brand="choice", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Fairfield Inn & Suites Indianapolis South Greenwood",
       "1190 North State Road 135", "Greenwood", "46142",
       brand="marriott", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("La Quinta Inn & Suites Indianapolis South Greenwood",
       "1281 South Park Drive", "Greenwood", "46143",
       brand="wyndham", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Quality Inn Greenwood Indianapolis South",
       "1101 Ramblin Road", "Greenwood", "46142",
       brand="choice", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Super 8 by Wyndham Greenwood Indianapolis South",
       "110 South State Road 135", "Greenwood", "46142",
       brand="wyndham", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Home2 Suites by Hilton Indianapolis Greenwood",
       "497 Airtech Parkway", "Greenwood", "46143",
       brand="hilton", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
    _c("Hilton Garden Inn Indianapolis South Greenwood",
       "525 Airtech Parkway", "Greenwood", "46143",
       brand="hilton", county="Johnson", identity="IDENTITY_PROVISIONAL",
       source="brand_locator_research", routing="BRAND_INDEX_OR_CITY_LOCATOR"),
]


DISPOSITIONS: List[Dict] = [
    {
        "canonical_name": "Marriott IndyPlace",
        "address": "701 East 83rd Avenue",
        "city": "Indianapolis",
        "disposition": "confirmed_duplicate",
        "duplicate_of": "JW Marriott Indianapolis",
        "rationale": "Downtown Indy, Inc. lists Marriott IndyPlace as a campus name. Visit Indy describes IndyPlace as five interconnected Marriott hotels whose sleeping-room identities are already in the census (JW Marriott, Courtyard Downtown, SpringHill Suites Downtown, Fairfield Inn Downtown, plus the Indianapolis Marriott Downtown). The 701 E 83rd Avenue string is a Castleton-area address and is treated as a directory transcription error, not a sixth hotel.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "GentSpa Hilton Indianapolis",
        "address": "",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Downtown Indy, Inc. lists GentSpa as a spa at Hilton Indianapolis, not lodging. Removed from the hotel filter of the same directory.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "The Harney House Inn",
        "address": "345 North East Street",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Bed and breakfast. Current PetTripFinder category is hotels, motels, and extended-stay lodging.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "The Looking Glass Inn",
        "address": "1319 North New Jersey Street",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Bed and breakfast. Out of current category.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Nestle Inn",
        "address": "637 North East Street",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Bed and breakfast. Out of current category.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Old Northside Bed and Breakfast",
        "address": "1340 North Alabama Street",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Bed and breakfast. Out of current category.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Stone Soup Inn",
        "address": "1304 North Central Avenue",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Bed and breakfast. Out of current category.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Fountainview Inn",
        "address": "1105 Prospect Street",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Inn / B&B in Fountain-Fletcher. Out of current hotel category. This is why Fountain-Fletcher is not a lodging corridor.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "The Columbia Club",
        "address": "121 Monument Circle",
        "city": "Indianapolis",
        "disposition": "category_excluded",
        "rationale": "Private club with member lodging, not a public hotel in the current category.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Park Place at City Centre",
        "address": "1150 North White River Parkway",
        "city": "Indianapolis",
        "disposition": "identity_unresolved",
        "rationale": "Downtown Indy, Inc. lists the name. It is not confirmed as a public hotel versus residential / extended-stay apartments, so it is held out of the canonical census.",
        "source": "downtown_indy_inc",
    },
    {
        "canonical_name": "Signia by Hilton Indianapolis",
        "address": "",
        "city": "Indianapolis",
        "disposition": "closed_or_converted",
        "rationale": "Visit Indy connected-hotels page states the Signia Hilton is expected to open in 2026 and is not an operating hotel in this factory's observation window.",
        "source": "visit_indy",
    },
    {
        "canonical_name": "Holiday Inn Express Airport West",
        "address": "",
        "city": "Indianapolis",
        "disposition": "confirmed_duplicate",
        "duplicate_of": "Holiday Inn Indianapolis Airport",
        "rationale": "Indianapolis Airport Authority courtesy-vehicle table lists Holiday Inn Airport Area and Holiday Inn Express Airport West on the same IHG URL and the same phone number (317-478-2088). Treated as one identity until a property-level page distinguishes them.",
        "source": "indianapolis_airport",
    },
    {
        "canonical_name": "Baymont by Wyndham Lawrenceburg",
        "address": "",
        "city": "Lawrenceburg",
        "disposition": "boundary_excluded",
        "rationale": "Dearborn County Indiana lodging already owned by cincinnati-oh (ZIP 47025).",
        "source": "cincinnati_oh_census",
    },
    {
        "canonical_name": "DoubleTree by Hilton Lawrenceburg",
        "address": "",
        "city": "Lawrenceburg",
        "disposition": "boundary_excluded",
        "rationale": "Dearborn County Indiana lodging already owned by cincinnati-oh.",
        "source": "cincinnati_oh_census",
    },
]
