"""PTF-NASHVILLE-TN-PROMOTION-AND-NEW-LANE-LAUNCH-PREP-002 -- the shared registries.

Registering a market touches three documents that belong to every market, and
each is edited here rather than by hand so the change is auditable and
re-runnable:

  deploy/netlify/launch_participation.json    a row for the new market
  launch_packages/pettripfinder/bundle_cache_closure.json   its two declared inputs
  (the three generated globals are regenerated by market_authority itself)

WHAT IT DOES NOT DO

It does not authorize Nashville for launch. The row it writes says
SOURCE_READY_BUT_NOT_FOUNDER_AUTHORIZED_FOR_LAUNCH, which is the status the
participation contract defines for a market that passes every assembly
condition and is withheld by founder decision. It does not touch the
``decision`` block, which records the founder's OWN last decision and is not
this order's to restate. It does not change any other market's row.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import OrderedDict

_DASH = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
if _DASH not in sys.path:
    sys.path.insert(0, _DASH)

WORK_ORDER = "PTF-NASHVILLE-TN-PROMOTION-AND-NEW-LANE-LAUNCH-PREP-002"
SHADOW_ORDER = "PTF-NASHVILLE-TN-NEW-MARKET-001"
MARKET_ID = "nashville-tn"
STATUS = "SOURCE_READY_BUT_NOT_FOUNDER_AUTHORIZED_FOR_LAUNCH"

PKG = os.path.join(_DASH, "launch_packages", "pettripfinder")
PARTICIPATION = os.path.join(_DASH, "deploy", "netlify", "launch_participation.json")
CLOSURE = os.path.join(PKG, "bundle_cache_closure.json")


def _load(p):
    with open(p, encoding="utf-8-sig") as fh:
        return json.load(fh, object_pairs_hook=OrderedDict)


def _write(p, doc):
    with open(p, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write("\n")


def participation_note():
    census = _load(os.path.join(PKG, "identity_census", "%s.json" % MARKET_ID))
    policy = _load(os.path.join(PKG, "hotel_policy_facts_%s.json" % MARKET_ID))
    holds = _load(os.path.join(PKG, "nashville_tn_identity_holds_002.json"))
    exclusions = _load(os.path.join(PKG, "markets", "authority", MARKET_ID,
                                    "hotel_exclusions.json"))
    shadow = _load(os.path.join(PKG, "markets", "reports",
                                "nashville_tn_shadow_market_001.json"))["projected"]
    gates = "; ".join("%d %s" % (n, c)
                      for c, n in holds["counts_by_gate_classification"].items())
    return (
        "%d pet-friendly profiles and %d verified-no-pets exclusions over a %d-identity "
        "registered census, carried across from the %d-identity shadow %s built from zero for $0 "
        "and 17 Firecrawl credits. Registered by %s, whose count gate reproduced the shadow's "
        "%d / %d / %d / %d exactly before any row was removed; %d rows are then held by the "
        "registered census, cross-market, modern first-party evidence and paid-provenance gates "
        "and publish nothing (by gate: %s). The dominant hold is NO_CAPTURE_HASH: the shadow's "
        "attended lane read 154 pages for $0 and recorded a byte LENGTH rather than a document "
        "hash, so 84 otherwise-clean reads cannot be tied to a document and cannot publish. "
        "NOT AUTHORIZED for launch: no founder decision exists for Nashville. This row states "
        "only that the source passes every assembly condition. Hidden from global navigation and "
        "from the market listing (show_in_navigation=false, show_in_sitemap=false), exactly as "
        "live Louisville, Cincinnati, Toledo and Lexington are. 0 of its 19 corridors reach their "
        "own publication minimum at this profile count, which is a threshold and not a gap."
        % (len(policy["hotels"]), exclusions["count"], census["count"], shadow["census"],
           SHADOW_ORDER, WORK_ORDER, shadow["census"], shadow["pet_friendly"],
           shadow["verified_no_pets"], shadow["unresolved"], holds["count"], gates))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    doc = _load(PARTICIPATION)
    rows = [m for m in doc["markets"] if m["market_id"] != MARKET_ID]
    if len(rows) != len(doc["markets"]) - (1 if len(rows) < len(doc["markets"]) else 0):
        raise RuntimeError("participation carries the market more than once")
    rows.append(OrderedDict([("market_id", MARKET_ID), ("launch_status", STATUS),
                             ("note", participation_note())]))
    rows.sort(key=lambda m: m["market_id"])
    doc["markets"] = rows

    closure = _load(CLOSURE)
    shared = list(closure["shared_data_inputs"])
    added = [p for p in ("deploy/netlify/release_contracts/%s.json" % MARKET_ID,
                         "launch_packages/pettripfinder/markets/%s.json" % MARKET_ID)
             if p not in shared]
    closure["shared_data_inputs"] = sorted(shared + added)
    closure["remeasured_by"] = list(closure["remeasured_by"]) + [
        "%s: the closure enumerates every REGISTERED market's contract and release contract by "
        "name, so registering Nashville extends it by exactly two paths. Until they are declared "
        "the cache calls them undeclared reads and publishes every bundle UNTRUSTED, which is the "
        "guard working: an unlisted input is an input nobody proved constant." % WORK_ORDER]

    print("participation : %d markets, %s -> %s" % (len(rows), MARKET_ID, STATUS))
    print("closure       : +%d shared data inputs (%d total)"
          % (len(added), len(closure["shared_data_inputs"])))
    if args.check:
        print("nothing written (--check)")
        return 0
    _write(PARTICIPATION, doc)
    _write(CLOSURE, closure)
    print("written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
