"""PTF-MARKET-AUTHORITY-SHARDING-001 -- the one-time split.

Reads the three legacy global authority files as committed on main and writes
each market's records into its own shard under
``launch_packages/pettripfinder/markets/authority/<market_id>/``.

This script is a MOVE, not a rewrite. Records are copied verbatim -- same
fields, same values, same key order, same relative order within a market -- so
that reassembling the shards produces the same record set the global files
already carried. Nothing is normalized, deduplicated, repaired or reformatted
on the way through; the only thing that changes is which file a record lives in.

Run once:

    python -m scripts.pettripfinder.shard_market_authority_001 --write

It is idempotent: running it again against unchanged globals rewrites identical
shards. After the split, the global files are regenerated by
``build_global_authority.py`` and every subsequent market work order writes only
its own shard.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Dict, List

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.pettripfinder import market_authority as MA   # noqa: E402

#: The global routing document carried one flat ``source_batches`` list for all
#: markets. Each batch belongs to exactly one market, so the split is stated
#: explicitly here rather than inferred from the batch name -- a heuristic on a
#: provenance field is how provenance quietly becomes wrong.
_ROUTING_SOURCE_BATCHES: Dict[str, List[str]] = {
    "columbus-oh": ["columbus-official-url-recovery-001",
                    "columbus-official-url-apply-001"],
    "cleveland-akron-canton-oh": ["ptf-cleveland-url-recovery-002-batch1",
                                  "cleveland-work-browser-pass-001"],
    "dayton-oh": ["dayton-work-browser-001"],
    "cincinnati-oh": ["cincinnati-url-routing-recovery-001c"],
}


def split(write: bool) -> int:
    market_ids = MA.registered_market_ids()

    routing_doc = json.loads(MA.GLOBAL_ROUTING_PATH.read_text(encoding="utf-8-sig"))
    exclusions_doc = json.loads(MA.GLOBAL_EXCLUSIONS_PATH.read_text(encoding="utf-8-sig"))
    with MA.GLOBAL_SEED_PATH.open(encoding="utf-8", newline="") as f:
        seed_rows = [dict(r) for r in csv.DictReader(f)]

    declared_batches = list(routing_doc.get("source_batches") or [])
    mapped = [b for batches in _ROUTING_SOURCE_BATCHES.values() for b in batches]
    if sorted(declared_batches) != sorted(mapped):
        raise SystemExit(
            "source_batches on the global routing document (%s) do not match the "
            "explicit per-market split (%s). Update _ROUTING_SOURCE_BATCHES "
            "deliberately -- provenance is never dropped to make a script run."
            % (declared_batches, mapped))

    unknown = sorted({r.get("market_id") for r in routing_doc["routes"]} |
                     {e.get("market_id") for e in exclusions_doc["exclusions"]} |
                     {s.get("market_id") for s in seed_rows})
    unknown = [m for m in unknown if m not in market_ids]
    if unknown:
        raise SystemExit("records name unregistered market(s): %s" % unknown)

    for market_id in market_ids:
        routes = [r for r in routing_doc["routes"] if r.get("market_id") == market_id]
        exclusions = [e for e in exclusions_doc["exclusions"]
                      if e.get("market_id") == market_id]
        rows = [r for r in seed_rows if r.get("market_id") == market_id]

        routing_shard = MA.build_routing_shard(
            market_id, routes, _ROUTING_SOURCE_BATCHES.get(market_id, []))
        exclusions_shard = MA.build_exclusions_shard(market_id, exclusions)

        print("%-28s routes=%-4d exclusions=%-3d seed=%d"
              % (market_id, len(routes), len(exclusions), len(rows)))
        if not write:
            continue

        MA.market_shard_dir(market_id).mkdir(parents=True, exist_ok=True)
        for path, text in (
            (MA.routing_shard_path(market_id), MA.render_json(routing_shard)),
            (MA.exclusions_shard_path(market_id), MA.render_json(exclusions_shard)),
            (MA.seed_shard_path(market_id), MA.render_seed_csv(rows)),
        ):
            with path.open("wb") as f:
                f.write(text.encode("utf-8"))

    if not write:
        print("\ndry run: pass --write to create the shards")
        return 0

    print("\nreassembling and verifying...")
    assembled_routes = MA.assemble_routing_document()["routes"]
    assembled_exclusions = MA.assemble_exclusions_document()["exclusions"]
    assembled_seed = MA.assemble_seed_rows()

    def canonical(records):
        return sorted(json.dumps(r, sort_keys=True, ensure_ascii=False)
                      for r in records)

    for label, before, after in (
        ("routes", routing_doc["routes"], assembled_routes),
        ("exclusions", exclusions_doc["exclusions"], assembled_exclusions),
        ("seed rows", seed_rows, assembled_seed),
    ):
        if canonical(before) != canonical(after):
            raise SystemExit("%s are NOT equivalent after the split" % label)
        print("  %-11s %d -> %d  EQUIVALENT" % (label, len(before), len(after)))
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="write the shards (default is a dry run)")
    args = parser.parse_args(argv)
    return split(args.write)


if __name__ == "__main__":   # pragma: no cover
    raise SystemExit(main())
