"""
Website template engine.

This module is intentionally deterministic.

It does NOT perform rendering decisions.

It simply exposes reusable HTML fragments used by the
StaticSiteGenerator.

Version 1 ships with exactly one approved template.

Future templates may be added without modifying the
generator itself.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import escape


@dataclass(frozen=True)
class WebsiteTemplate:
    name: str
    page_width: str
    navigation_style: str
    card_style: str
    footer_style: str


DEFAULT_TEMPLATE = WebsiteTemplate(
    name="clean_directory_v1",
    page_width="1200px",
    navigation_style="simple",
    card_style="directory_card",
    footer_style="minimal",
)


def render_head(title: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport"
      content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet"
      href="/assets/css/site.css">
</head>
<body>
"""


def render_header(site_name: str) -> str:
    return f"""
<header class="site-header">
<h1>{escape(site_name)}</h1>
</header>
"""


def render_navigation() -> str:
    return """
<nav class="site-nav">
<a href="/">Home</a>
</nav>
"""


def render_footer() -> str:
    return """
<footer class="site-footer">
<p>Generated by Atlas Website Generator</p>
</footer>
</body>
</html>
"""


def render_page(title: str, site_name: str, body: str) -> str:
    return (
        render_head(title)
        + render_header(site_name)
        + render_navigation()
        + body
        + render_footer()
    )
