"""Public contract surface of the Demand Mapping subsystem (AES-SEO-001).

Phase A: contracts only. Everything importable here is a frozen model, a
closed enum, a validator, or a canonicalization/identity helper. There is
no behavior beyond validation and canonical hashing.
"""

from engines.demand_mapping.contracts.canonical import (
    ContractCanonicalizationError,
    ContractValidationError,
    DemandMappingContractError,
    FrozenModel,
    PYDANTIC_V2,
    SchemaRegistrationError,
    canonical_contract_json,
    canonical_json,
    contract_sha256,
    model_from_dict,
    model_to_dict,
    sha256_of_text,
)
from engines.demand_mapping.contracts.provenance import (
    CONFIDENCE_BP_MAX,
    CONFIDENCE_BP_MIN,
    PROVENANCE_PRIORITY,
    Provenance,
    TaggedValue,
    merge_tagged_values,
    stronger_provenance,
    validate_confidence_bp,
    validate_tagged_value,
)
from engines.demand_mapping.contracts.evidence import (
    EvidenceObservation,
    EvidenceSnapshot,
    ObservationType,
    compute_observation_id,
    compute_snapshot_id,
    validate_observation,
    validate_snapshot,
)
from engines.demand_mapping.contracts.dimensions import (
    CoOccurrence,
    DimensionKind,
    DimensionProfile,
    DimensionProfileSet,
    FrequencyEntry,
    NumericSummary,
    ProvenanceCoverage,
    compute_profile_set_id,
    validate_dimension_profile,
    validate_dimension_profile_set,
)
from engines.demand_mapping.contracts.opportunities import (
    CandidateQuery,
    ClusterRelation,
    ClusterRelationKind,
    ContentFeasibility,
    DecisionState,
    DimensionValueRef,
    FactRequirement,
    GateOutcome,
    GateResult,
    IntentClass,
    InventorySupport,
    OpportunityFamily,
    PageOpportunity,
    PageOpportunitySet,
    RiskFlag,
    TargetConcept,
    compute_opportunity_id,
    compute_opportunity_set_id,
    validate_page_opportunity,
    validate_page_opportunity_set,
)
from engines.demand_mapping.contracts.records import (
    FieldValue,
    GenericEntityRecord,
    GenericInventorySnapshot,
    compute_inventory_snapshot_id,
    validate_entity_record,
    validate_field_value,
    validate_inventory_snapshot,
)
from engines.demand_mapping.contracts.versions import (
    CONTRACTS_VERSION,
    ENGINE_VERSIONS,
    EVIDENCE_MODEL_VERSION,
    SCHEMA_VERSIONS,
    register_schema,
    registered_schema,
    registered_schema_versions,
)

__all__ = [
    # canonical
    "ContractCanonicalizationError",
    "ContractValidationError",
    "DemandMappingContractError",
    "FrozenModel",
    "PYDANTIC_V2",
    "SchemaRegistrationError",
    "canonical_contract_json",
    "canonical_json",
    "contract_sha256",
    "model_from_dict",
    "model_to_dict",
    "sha256_of_text",
    # provenance
    "CONFIDENCE_BP_MAX",
    "CONFIDENCE_BP_MIN",
    "PROVENANCE_PRIORITY",
    "Provenance",
    "TaggedValue",
    "merge_tagged_values",
    "stronger_provenance",
    "validate_confidence_bp",
    "validate_tagged_value",
    # evidence
    "EvidenceObservation",
    "EvidenceSnapshot",
    "ObservationType",
    "compute_observation_id",
    "compute_snapshot_id",
    "validate_observation",
    "validate_snapshot",
    # dimensions
    "CoOccurrence",
    "DimensionKind",
    "DimensionProfile",
    "DimensionProfileSet",
    "FrequencyEntry",
    "NumericSummary",
    "ProvenanceCoverage",
    "compute_profile_set_id",
    "validate_dimension_profile",
    "validate_dimension_profile_set",
    # opportunities
    "CandidateQuery",
    "ClusterRelation",
    "ClusterRelationKind",
    "ContentFeasibility",
    "DecisionState",
    "DimensionValueRef",
    "FactRequirement",
    "GateOutcome",
    "GateResult",
    "IntentClass",
    "InventorySupport",
    "OpportunityFamily",
    "PageOpportunity",
    "PageOpportunitySet",
    "RiskFlag",
    "TargetConcept",
    "compute_opportunity_id",
    "compute_opportunity_set_id",
    "validate_page_opportunity",
    "validate_page_opportunity_set",
    # records
    "FieldValue",
    "GenericEntityRecord",
    "GenericInventorySnapshot",
    "compute_inventory_snapshot_id",
    "validate_entity_record",
    "validate_field_value",
    "validate_inventory_snapshot",
    # versions
    "CONTRACTS_VERSION",
    "ENGINE_VERSIONS",
    "EVIDENCE_MODEL_VERSION",
    "SCHEMA_VERSIONS",
    "register_schema",
    "registered_schema",
    "registered_schema_versions",
]
