"""Contracts for the Website Generation Engine (AES-WEB-001 Phase 1).

The only package every other WGE package may import: artifact models,
enums, typed errors, version registries, and the canonical serialization
helpers. No logic beyond what the contracts themselves require.
"""

from engines.website_generation.contracts.artifacts import (
    ArtifactHeader,
    BrandPackage,
    BuildManifest,
    BusinessSpec,
    ComponentInstance,
    ComponentManifest,
    ContentBlock,
    ContentCandidate,
    ContentPackage,
    FrozenModel,
    GateResult,
    LaunchCertificateBody,
    LayoutPlan,
    LayoutRegion,
    PageComponents,
    PageLayout,
    PagePlan,
    QualityReport,
    RenderedPage,
    RenderedPageSet,
    SEOEntry,
    SEOPackage,
    SiteArchitecture,
    SiteBundle,
    SpecCompilerInput,
    StageRecord,
    TransitionRecord,
    artifact_sha256,
    canonical_artifact_json,
    canonical_json,
    model_from_dict,
    model_to_dict,
    sha256_of_text,
)
from engines.website_generation.contracts.enums import (
    ArtifactKind,
    ArtifactLifecycleState,
    BuildState,
    GateSeverity,
    StageExecutionStatus,
    StageOutcome,
)
from engines.website_generation.contracts.errors import (
    ArtifactIntegrityError,
    ArtifactNotFoundError,
    ArtifactValidationError,
    IllegalTransitionError,
    RepositoryCorruptionError,
    SchemaRegistrationError,
    SpecCompilationError,
    UnsupportedSchemaVersionError,
    WebsiteGenerationError,
)
from engines.website_generation.contracts.interfaces import (
    SpecCompilerInterface,
)
from engines.website_generation.contracts.versions import (
    ENGINE_VERSIONS,
    SCHEMA_VERSIONS,
    register_artifact_model,
    registered_artifact_model,
    registered_schema_versions,
)

__all__ = [
    # models
    "ArtifactHeader",
    "BrandPackage",
    "BuildManifest",
    "BusinessSpec",
    "ComponentInstance",
    "ComponentManifest",
    "ContentBlock",
    "ContentCandidate",
    "ContentPackage",
    "FrozenModel",
    "GateResult",
    "LaunchCertificateBody",
    "LayoutPlan",
    "LayoutRegion",
    "PageComponents",
    "PageLayout",
    "PagePlan",
    "QualityReport",
    "RenderedPage",
    "RenderedPageSet",
    "SEOEntry",
    "SEOPackage",
    "SiteArchitecture",
    "SiteBundle",
    "SpecCompilerInput",
    "StageRecord",
    "TransitionRecord",
    # serialization
    "artifact_sha256",
    "canonical_artifact_json",
    "canonical_json",
    "model_from_dict",
    "model_to_dict",
    "sha256_of_text",
    # enums
    "ArtifactKind",
    "ArtifactLifecycleState",
    "BuildState",
    "GateSeverity",
    "StageExecutionStatus",
    "StageOutcome",
    # errors
    "ArtifactIntegrityError",
    "ArtifactNotFoundError",
    "ArtifactValidationError",
    "IllegalTransitionError",
    "RepositoryCorruptionError",
    "SchemaRegistrationError",
    "SpecCompilationError",
    "UnsupportedSchemaVersionError",
    "WebsiteGenerationError",
    # interfaces
    "SpecCompilerInterface",
    # registries
    "ENGINE_VERSIONS",
    "SCHEMA_VERSIONS",
    "register_artifact_model",
    "registered_artifact_model",
    "registered_schema_versions",
]
