"""Contracts for the Website Generation Engine (AES-WEB-001 Phase 1).

The only package every other WGE package may import: artifact models,
enums, typed errors, version registries, and the canonical serialization
helpers. No logic beyond what the contracts themselves require.
"""

from engines.website_generation.contracts.artifacts import (
    ArtifactHeader,
    BrandPackage,
    BuildManifest,
    BusinessSpec,
    ComponentInstance,
    ComponentManifest,
    ContentBlock,
    ContentCandidate,
    ContentPackage,
    FrozenModel,
    GateResult,
    LaunchCertificateBody,
    LayoutPlan,
    LayoutRegion,
    PageComponents,
    PageLayout,
    PagePlan,
    QualityReport,
    RenderedPage,
    RenderedPageSet,
    SEOEntry,
    SEOPackage,
    SelectionCandidate,
    SelectionScoreComponent,
    SelectionTrace,
    SiteArchitecture,
    SiteBundle,
    SlotSelectionTrace,
    SpecCompilerInput,
    StageRecord,
    TransitionRecord,
    artifact_sha256,
    canonical_artifact_json,
    canonical_json,
    model_from_dict,
    model_to_dict,
    sha256_of_text,
)
from engines.website_generation.contracts.components import (
    AccessibilityContract,
    AnalyticsContract,
    ComponentDefinition,
    ConversionContract,
    DeprecationInfo,
    DirectoryContract,
    MonetizationContract,
    PropSpec,
    RenderingContract,
    ResponsiveContract,
    SEOContract,
    SlotSpec,
    VariantSpec,
)
from engines.website_generation.contracts.enums import (
    ArtifactKind,
    ArtifactLifecycleState,
    AssetRole,
    BuildState,
    CommercialPurpose,
    ComponentFamily,
    ConversionGoal,
    GateSeverity,
    LifecycleStatus,
    ListingKind,
    PageRole,
    PropType,
    RegionKind,
    SemanticElement,
    SlotCardinality,
    StageExecutionStatus,
    StageOutcome,
)
from engines.website_generation.contracts.errors import (
    ArtifactIntegrityError,
    ArtifactNotFoundError,
    ArtifactValidationError,
    ComponentNotFoundError,
    ComponentSystemError,
    ConflictingComponentError,
    DuplicateComponentError,
    IllegalTransitionError,
    InvalidCompatibilityDeclarationError,
    InvalidComponentDefinitionError,
    RepositoryCorruptionError,
    SchemaRegistrationError,
    SpecCompilationError,
    UnsupportedComponentVersionError,
    UnsupportedSchemaVersionError,
    WebsiteGenerationError,
)
from engines.website_generation.contracts.interfaces import (
    ComponentRegistryView,
    SpecCompilerInterface,
)
from engines.website_generation.contracts.versions import (
    COMPONENT_CONTRACT_SCHEMA_VERSION,
    COMPONENT_SYSTEM_VERSIONS,
    ENGINE_VERSIONS,
    REGISTRY_FINGERPRINT_VERSION,
    REGISTRY_VERSION,
    SCHEMA_VERSIONS,
    register_artifact_model,
    registered_artifact_model,
    registered_schema_versions,
)

__all__ = [
    # models
    "ArtifactHeader",
    "BrandPackage",
    "BuildManifest",
    "BusinessSpec",
    "ComponentInstance",
    "ComponentManifest",
    "ContentBlock",
    "ContentCandidate",
    "ContentPackage",
    "FrozenModel",
    "GateResult",
    "LaunchCertificateBody",
    "LayoutPlan",
    "LayoutRegion",
    "PageComponents",
    "PageLayout",
    "PagePlan",
    "QualityReport",
    "RenderedPage",
    "RenderedPageSet",
    "SEOEntry",
    "SEOPackage",
    "SelectionCandidate",
    "SelectionScoreComponent",
    "SelectionTrace",
    "SiteArchitecture",
    "SiteBundle",
    "SlotSelectionTrace",
    "SpecCompilerInput",
    "StageRecord",
    "TransitionRecord",
    # component contracts (AES-WEB-002A)
    "AccessibilityContract",
    "AnalyticsContract",
    "ComponentDefinition",
    "ConversionContract",
    "DeprecationInfo",
    "DirectoryContract",
    "MonetizationContract",
    "PropSpec",
    "RenderingContract",
    "ResponsiveContract",
    "SEOContract",
    "SlotSpec",
    "VariantSpec",
    # serialization
    "artifact_sha256",
    "canonical_artifact_json",
    "canonical_json",
    "model_from_dict",
    "model_to_dict",
    "sha256_of_text",
    # enums
    "ArtifactKind",
    "ArtifactLifecycleState",
    "BuildState",
    "GateSeverity",
    "StageExecutionStatus",
    "StageOutcome",
    # component enums (AES-WEB-002A)
    "AssetRole",
    "CommercialPurpose",
    "ComponentFamily",
    "ConversionGoal",
    "LifecycleStatus",
    "ListingKind",
    "PageRole",
    "PropType",
    "RegionKind",
    "SemanticElement",
    "SlotCardinality",
    # errors
    "ArtifactIntegrityError",
    "ArtifactNotFoundError",
    "ArtifactValidationError",
    "IllegalTransitionError",
    "RepositoryCorruptionError",
    "SchemaRegistrationError",
    "SpecCompilationError",
    "UnsupportedSchemaVersionError",
    "WebsiteGenerationError",
    # component errors (AES-WEB-002A)
    "ComponentNotFoundError",
    "ComponentSystemError",
    "ConflictingComponentError",
    "DuplicateComponentError",
    "InvalidCompatibilityDeclarationError",
    "InvalidComponentDefinitionError",
    "UnsupportedComponentVersionError",
    # interfaces
    "ComponentRegistryView",
    "SpecCompilerInterface",
    # registries
    "ENGINE_VERSIONS",
    "SCHEMA_VERSIONS",
    "register_artifact_model",
    "registered_artifact_model",
    "registered_schema_versions",
    # component-system versions (AES-WEB-002A)
    "COMPONENT_CONTRACT_SCHEMA_VERSION",
    "COMPONENT_SYSTEM_VERSIONS",
    "REGISTRY_FINGERPRINT_VERSION",
    "REGISTRY_VERSION",
]
